service: observability-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: production
  region: eu-central-1
  timeout: 30
  memorySize: 256
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - "schedule:ListSchedules"
            - "schedule:GetSchedule"
            - "schedule:CreateSchedule"
            - "schedule:UpdateSchedule"
            - "schedule:DeleteSchedule"
            - "scheduler:ListScheduleGroups"
            - "scheduler:GetScheduleGroup"
            - "scheduler:CreateScheduleGroup"
            - "scheduler:DeleteScheduleGroup"
            - "scheduler:ListTagsForResource"
            - "scheduler:TagResource"
            - "scheduler:UntagResource"
          Resource: '*'
functions:
  app:
    handler: dist/lambda.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true